LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := bme280
LOCAL_SRC_FILES := bme280.c
LOCAL_C_INCLUDES := $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/usr/include/
LOCAL_C_INCLUDES += $(LOCAL_PATH)/
LOCAL_SHARED_LIBRARIES := libc
include $(BUILD_EXECUTABLE)
